stages:
  - test

cypress:
  stage: test
  image: cypress/browsers:node18.16.0-chrome118-ff120  # Node + Chrome + Firefox
  script:
    - npm ci
    - npx cypress run --browser chrome
  artifacts:
    paths:
      - cypress/videos
      - cypress/screenshots
