pipelines:
  default:
    - step:
        image: cypress/browsers:node18.16.0-chrome118-ff120
        script:
          - npm ci
          - xvfb-run -a npx cypress run --browser chrome --headed
            --spec "cypress/e2e/AgentStatusTest.cy.js"
        artifacts:
          - cypress/videos/** 
          - cypress/screenshots/**

