pipelines:
  default:
    - step:
        name: Cypress Tests
        image: cypress/browsers:node18.16.0-chrome118-ff120
        caches:
          - node
        script:
          - npm ci
          - npx cypress run --browser chrome
        artifacts: 
          - cypress/videos/**
          - cypress/screenshots/**

